version: "3"

services:
    elm:
        build: docker
        entrypoint: elm
        command: --help
        ports:
            - 8000:8000
        volumes:
            - .:/home/user/app

    yarn:
        build: docker
        entrypoint: yarn
        command: --help
        volumes:
            - .:/home/user/app

    node:
        build: docker
        entrypoint: node
        command: --help
        volumes:
            - .:/home/user/app

    npm:
        build: docker
        entrypoint: npm
        command: --help
        volumes:
            - .:/home/user/app

    npx:
        build: docker
        entrypoint: npx
        command: --help
        volumes:
            - .:/home/user/app
